import { conditions, expr, step, workflow } from "../../src/mod.ts";

const header = "# GENERATED by .github/workflows/ci.ts -- do not edit manually";

const isForkPR = expr("github.event.pull_request.head.label")
  .startsWith("dsherret:");
const skipForForkPRs = conditions.isEvent("push").or(isForkPR.not());

const checkout = step({ uses: "actions/checkout@v6" });
const setupDeno = step({
  uses: "denoland/setup-deno@v2",
  with: { "deno-version": "canary" },
});

const isTag = conditions.isTag();
const isTagOnLinux = isTag.and(conditions.isRunnerOs("Linux"));

const getTagVersion = step({
  id: "get_tag_version",
  name: "Get tag version",
  if: isTagOnLinux,
  run: "echo TAG_VERSION=${GITHUB_REF/refs\\/tags\\//} >> $GITHUB_OUTPUT",
  outputs: ["TAG_VERSION"],
}).dependsOn(checkout);

workflow({
  name: "ci",
  on: ["push", "pull_request"],
  concurrency: {
    group:
      "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}",
    cancelInProgress: true,
  },
  jobs: [
    {
      id: "deno",
      name: "gagen",
      if: skipForForkPRs,
      runsOn: "ubuntu-latest",
      timeoutMinutes: 30,
      steps: [
        checkout,
        setupDeno,
        { name: "fmt", run: "deno fmt --check" },
        { name: "lint", run: "deno lint" },
        { name: "test", run: "deno test -A" },
        { name: "lint ci", run: "deno run -A ./src/cli.ts --lint" },
      ],
    },
    {
      id: "jsr",
      runsOn: "ubuntu-latest",
      permissions: { contents: "read", "id-token": "write" },
      steps: [
        checkout,
        setupDeno,
        {
          name: "Publish to JSR on tag",
          run: "deno run -A jsr:@david/publish-on-tag@0.2.0",
        },
      ],
    },
    {
      id: "npm",
      runsOn: "ubuntu-latest",
      permissions: { contents: "read", "id-token": "write" },
      steps: [
        checkout,
        getTagVersion,
        {
          uses: "actions/setup-node@v6",
          with: {
            "node-version": "24.x",
            "registry-url": "https://registry.npmjs.org",
          },
        },
        {
          name: "npm build",
          run: `deno task build:npm ${getTagVersion.outputs.TAG_VERSION}`,
        },
        {
          name: "npm publish",
          if: isTagOnLinux,
          run: "cd npm && npm publish",
        },
      ],
    },
  ],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header,
});
